### ISSUE TITLE
Add optional typing

### ISSUE THREAD

**Issue by lausek** [lausek/lovm2#1]
## Todo

- [ ] allow emitting more than one error when lowering the hir
- [ ] introduce a feature-flag for typing support
- [ ] give each `Expr` an optional type
- [ ] check that there is no type violation when lowering
- [ ] respect type changes when casting

**Comment by lausek** [comment]
This should be implemented as a separate crate on top of the `HIR` to keep `lovm2` slim
